# Generated by Django 5.2.3 on 2025-06-23 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("habits", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="habits",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="habit",
            index=models.Index(fields=["user"], name="habits_habi_user_id_599ecd_idx"),
        ),
        migrations.AddIndex(
            model_name="habit",
            index=models.Index(
                fields=["is_pleasant"], name="habits_habi_is_plea_04f536_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="habit",
            index=models.Index(
                fields=["is_public"], name="habits_habi_is_publ_af85bc_idx"
            ),
        ),
    ]
