# Generated by Django 5.2.3 on 2025-06-23 20:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="habit",
            name="habits_habi_user_id_599ecd_idx",
        ),
        migrations.RenameField(
            model_name="habit",
            old_name="user",
            new_name="owner",
        ),
        migrations.AddIndex(
            model_name="habit",
            index=models.Index(fields=["owner"], name="habits_habi_owner_i_c2c5d4_idx"),
        ),
    ]
