# Generated by Django 5.2.3 on 2025-06-23 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0003_remove_habit_habits_habi_user_id_599ecd_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="time",
            field=models.TimeField(),
        ),
    ]
