# Generated by Django 5.2.3 on 2025-06-25 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0005_habitnotification"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="habit",
            options={"ordering": ["time"]},
        ),
    ]
