# Generated by Django 5.2.3 on 2025-06-25 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0006_alter_habit_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="habit",
            options={"ordering": ("time",)},
        ),
        migrations.AlterField(
            model_name="habit",
            name="execution_time",
            field=models.PositiveSmallIntegerField(
                help_text="Execution time in seconds (<=120s)"
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="frequency",
            field=models.PositiveSmallIntegerField(
                default=1, help_text="Frequency of habit execution in days"
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="is_public",
            field=models.BooleanField(
                default=False, help_text="Public habits can be seen by all users"
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="related_habit",
            field=models.ForeignKey(
                blank=True,
                help_text="Related pleasant habit (can't be used if reward is set)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="habits.habit",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="reward",
            field=models.CharField(
                blank=True,
                help_text="Rewad for completing the habit (can't be used with related habit)",
                max_length=255,
                null=True,
            ),
        ),
    ]
